### ISSUE TITLE
the aliyun server has been created

### ISSUE THREAD

**Issue by MrKingHH** [ACLoong/Meeting-Review#2]
###aliyun server has created
The aliyun public ip is **119.23.206.28.**
Ur username is ur **Chinese name**. 
Ur password is ur **Chinese name's abbreviation and apand 123**. 
If u want to install or update some softwares, u should ask every member who are using this vps before. This is a userful way to ensure everyone's vps's env is right. 
@hxlong941110 @jsondrm @throcean @wangqing1218 @zmzhouXJTU @Tina66 @July-zhang

**Comment by zmzhouXJTU** [comment]
OK , i know. I will have a try

**Comment by wangqing1218** [comment]
Ok, i think if some one needs to install software, he/she should post a request for it to admin.

**Comment by ghost** [comment]
Please remove the username and password information mentioned in the issue. It is too insecure

**Comment by ghost** [comment]
I have modify this issue, and delete the history

**Comment by wangqing1218** [comment]
I think this repo named **Meeting Review**, so we should talk about this here.
I suggest that, rename this repo to **documents**, or who has a better one?

**Comment by ghost** [comment]
What is the meaning of **Documents** ? The **Documents**  is unclear.

**Comment by wangqing1218** [comment]
@throcean I think **Documents** repository can store all of our docs, like our personal infos, review-meetings, and so on.

**Comment by ghost** [comment]
@wangqing1218 That is sounds good.
