### ISSUE TITLE
Update the Introduction.md to latest.

### ISSUE THREAD

**Issue by MrKingHH** [ACLoong/Meeting-Review#5]
**I think the Introduction.md and Introduction_zh.md should be placed here, and u should update it to latest. If u are free, can you move the introduction file to here ?**
@Tina66 @snowlixue @jsondrm @zmzhouXJTU @July-zhang

**Comment by wangqing1218** [comment]
OK. It's a great issue.

**Comment by zmzhouXJTU** [comment]
I will do it now
